version: "3.9"

services:

  vault_hunters_minecraft:
    build:
      context: ./
      dockerfile: docker/vault_hunters_minecraft/Dockerfile
    container_name: vault_hunters_minecraft
    image: vault_hunters_minecraft
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 6G
      MAX_MEMORY: 32G
    volumes:
    - ./data:/data

networks:
  default:
    name: vault_hunters_3_network
