version: "3.9"

services:

  vault_hunters:
    build:
      context: ./
      dockerfile: docker/vault_hunters/Dockerfile
    container_name: vault_hunters
    image: vault_hunters
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 16G
      MAX_MEMORY: 32G

    # RAM-DISK
    # volumes:
    # - ./ram_disk:/ram_disk
    # working_dir: /ram_disk

    # DATA FS:
    volumes:
    - ./data:/data
    working_dir: /data

networks:
  default:
    name: vault_hunters_network
